dist: focal

language : ruby

services:

  - postgresql


before_script:

  - "cp ./config/database.yml.travis ./config/database.yml"

  - "bundle exec rails db:create"

  - "bundle exec rails db:migrate"
script: skip
