dist: focal

language : ruby

services:
  - postgresql
before_script:
  - psql -c 'create database test_db;' -U postgres
env:
  global:
    # A different port must be used when not using the
    # default PostgreSQL:
    - PGPORT=5433
script:
  - echo "OK, I should not see this"
